
[General]
bypass-system = true
skip-proxy = 192.168.0.0/16,10.0.0.0/8,127.0.0.1/8,172.16.0.0/12,localhost
dns-server = system,223.5.5.5,8.8.8.8
fallback-dns = 1.1.1.1,9.9.9.9
dns-fallback = true
ipv6 = false
always-real-ip = apple.com,icloud.com

[Proxy Group]
节点选择 = select, 自动选择, 故障转移, 🇭🇰 香港手动, 🇸🇬 狮城手动, 🇯🇵 日本手动, 🇺🇸 美国手动, DIRECT
自动选择 = url-test
故障转移 = fallback
🇭🇰 香港手动 = select
🇸🇬 狮城手动 = select
🇯🇵 日本手动 = select
🇺🇸 美国手动 = select
苹果服务 = select, 节点选择, DIRECT
奈飞 = select, 节点选择, DIRECT
油管 = select, 节点选择, DIRECT
Emby = select, 节点选择, DIRECT
Github = select, 节点选择, DIRECT
国内网站 = select, DIRECT, 节点选择
漏网之鱼 = select, 节点选择, DIRECT

[Rule]
RULE-SET,applications,DIRECT
RULE-SET,private,DIRECT
RULE-SET,reject,REJECT
RULE-SET,icloud,苹果服务
RULE-SET,apple,苹果服务
RULE-SET,google,节点选择
RULE-SET,proxy,节点选择
RULE-SET,direct,DIRECT
RULE-SET,lancidr,DIRECT
RULE-SET,cncidr,国内网站
RULE-SET,telegramcidr,节点选择
RULE-SET,Netflix,奈飞
RULE-SET,YouTube,油管
RULE-SET,Emby,Emby
RULE-SET,Github,Github
RULE-SET,Domestic,国内网站
RULE-SET,Global,节点选择
RULE-SET,GlobalMedia,节点选择
RULE-SET,Microsoft,节点选择
MATCH,漏网之鱼

[Rule Set]
applications = https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.yaml
private = https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.yaml
reject = https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.yaml
icloud = https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.yaml
apple = https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.yaml
google = https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.yaml
proxy = https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.yaml
direct = https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.yaml
lancidr = https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.yaml
cncidr = https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.yaml
telegramcidr = https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.yaml
Netflix = https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/Netflix.yaml
YouTube = https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/YouTube.yaml
Emby = https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/Emby.yaml
Github = https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/Github.yaml
Domestic = https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/Domestic.yaml
Global = https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/Global.yaml
GlobalMedia = https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/GlobalMedia.yaml
Microsoft = https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/Microsoft.yaml
