[custom]
;不要随意改变关键字，否则会导致出错

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=🎯 全球直连,[]GEOSITE,private
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/1576495283/clash/refs/heads/list/Cloudflare.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=💬 Ai平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=💬 Ai平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=💬 Ai平台,https://raw.githubusercontent.com/1576495283/clash/refs/heads/list/AI.list
ruleset=📘 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list
ruleset=🪂 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=🕊️ Twitter(X),https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list
ruleset=🗣️ Facebook,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Facebook/Facebook.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=📢 谷歌🇨🇳Play下载,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=📢 谷歌🇨🇳Play服务,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=📢 谷歌🇨🇳Play服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=📢 谷歌🇨🇳,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCN.list
ruleset=📢 谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=💁 WhatApp,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Whatsapp/Whatsapp.list
ruleset=🌳 Amazon,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Amazon/Amazon.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=Ⓜ️ 微软Bing,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
;ruleset=🎶 网易音乐,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
;ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=📺 哔哩港澳台,https://raw.githubusercontent.com/1576495283/clash/refs/heads/list/blibiliIntl.list
;ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
;ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=📺 Disney,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🎬 HBO MAX,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/HBO/HBO.list
ruleset=🎵 Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
ruleset=🎥 Emby,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Emby/Emby.list
ruleset=🎥 Emby,https://raw.githubusercontent.com/1576495283/clash/refs/heads/list/emotnstore.list
;ruleset=👌 虚拟币,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OKX/OKX.list
ruleset=👌 虚拟币,https://raw.githubusercontent.com/suanyao/clash/refs/heads/main/okx.list
;ruleset=👌 虚拟币,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/xnb.list
ruleset=⏱️ 检测,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Check.list
ruleset=🌍 国外,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Proxy.list
ruleset=🌍 国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list
ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🎯 全球直连,https://raw.githubusercontent.com/1576495283/clash/refs/heads/list/Direct.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Direct.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaMax/ChinaMax.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]DIRECT
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,5,300
custom_proxy_group=🚀 手动切换`select`.*
;custom_proxy_group=🔯 故障转移`fallback`.*`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=🔮 负载均衡`load-balance`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换`[]DIRECT
custom_proxy_group=💬 Ai平台`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📘 GitHub`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🪂 TikTok`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📲 电报消息`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🕊️ Twitter(X)`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🗣️ Facebook`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🚀 节点选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换
custom_proxy_group=📢 谷歌🇨🇳Play下载`select`[]🚀 节点选择`[]DIRECT`[]♻️ 自动选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换
custom_proxy_group=📢 谷歌🇨🇳Play服务`select`[]🚀 节点选择`[]DIRECT`[]♻️ 自动选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换
custom_proxy_group=📢 谷歌🇨🇳`select`[]DIRECT`[]🚀 节点选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换
custom_proxy_group=📢 谷歌`select`[]🚀 节点选择`[]DIRECT`[]♻️ 自动选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换
custom_proxy_group=💁 WhatApp`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🌳 Amazon`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软Bing`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软云盘`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🚀 手动切换
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🚀 节点选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换
custom_proxy_group=📺 Disney`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎥 奈飞视频`select`[]🎥 奈飞节点`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎬 HBO MAX`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎵 Spotify`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇮🇳 印度自动`[]🇮🇳 印度手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换`[]DIRECT
;custom_proxy_group=📺 巴哈姆特`select`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🚀 节点选择`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📺 哔哩港澳台`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎥 Emby`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换`[]DIRECT
custom_proxy_group=👌 虚拟币`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换`[]DIRECT
custom_proxy_group=⏱️ 检测`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🌍 国外`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换`[]DIRECT
;custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🚀 手动切换
;custom_proxy_group=🎶 网易音乐`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`[]🇸🇬 狮城自动`[]🇸🇬 狮城手动`[]🇭🇰 香港自动`[]🇭🇰 香港手动`[]🇨🇳 台湾自动`[]🇨🇳 台湾手动`[]🇯🇵 日本自动`[]🇯🇵 日本手动`[]🇺🇲 美国自动`[]🇺🇲 美国手动`[]🇰🇷 韩国自动`[]🇰🇷 韩国手动`[]🌏 其他自动`[]🌏 其他手动`[]🚀 手动切换
custom_proxy_group=🇭🇰 香港自动`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本自动`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国自动`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇨🇳 台湾自动`url-test`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 狮城自动`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国自动`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇮🇳 印度自动`url-test`(IN|India|Mumbai|Delhi|^IN(?!DONESIA)|(?<!印)印度(?!尼)|孟买|德里|印度-西部|其他-印度)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🌏 其他自动`url-test`(波|波兰|柬|柬埔寨|尼|尼泊尔|也|也门|克|克罗地亚|比|比利时|尔|阿尔及尔|立|立陶宛|冰|冰岛|秘|秘鲁|耳|阿尔巴尼亚|利|利比亚|埃|埃及|希|希腊|孟|孟加拉|芬|芬兰|愛|爱尔兰|澳|澳大利亚|英|英国|德|德国|南|南非|意|意大利|法|法国|拿|加拿大|墨|墨西哥|印|印度尼西亚|越|越南|俄|俄罗斯|瑞|瑞士|智|智利|荷|荷兰|巴|巴西|沙|沙特|班|班加罗尔|泰|泰国|烏|乌克兰|以|以色列|Australia|Konghwaguk)`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=🇭🇰 香港手动`select`(Hong[\s]?Kong|港|HK)
custom_proxy_group=🇯🇵 日本手动`select`(日本|东京|大阪|JP|Japan|埼玉)
custom_proxy_group=🇺🇲 美国手动`select`(美|洛杉矶|达拉斯|US\b|United States)
custom_proxy_group=🇨🇳 台湾手动`select`(台湾|台北|新北|彰化|TW|Taiwan)
custom_proxy_group=🇸🇬 狮城手动`select`(新加坡|狮城|SG|Singapore)
custom_proxy_group=🇰🇷 韩国手动`select`(韩|Korea|KR|首尔)
custom_proxy_group=🇮🇳 印度手动`select`(孟买|德里|(?<!印)印度(?!尼)|India|^IN(?!DONESIA))
custom_proxy_group=🌏 其他手动`select`(波|波兰|柬|柬埔寨|尼|尼泊尔|也|也门|克|克罗地亚|比|比利时|尔|阿尔及尔|立|立陶宛|冰|冰岛|秘|秘鲁|耳|阿尔巴尼亚|利|利比亚|埃|埃及|希|希腊|孟|孟加拉|芬|芬兰|愛|爱尔兰|澳|澳大利亚|英|英国|德|德国|南|南非|意|意大利|法|法国|拿|加拿大|墨|墨西哥|印|印度尼西亚|越|越南|俄|俄罗斯|瑞|瑞士|智|智利|荷|荷兰|巴|巴西|沙|沙特|班|班加罗尔|泰|泰国|烏|乌克兰|以|以色列|Australia|Konghwaguk)
custom_proxy_group=🎥 奈飞节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media)
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true
